### ISSUE TITLE
Test Miu on ARM 32/64 platform

### ISSUE THREAD

**Issue by bootstrapsp** [bootstrapsp/miu#29]
Test Miu on ARM 32/64 platforms like Raspi, to find what effort is needed in making it low powered device ready.

**Why**
This will allow seamless experience on variety of platforms for Miu.

**Comment by bootstrapsp** [comment]
installing from requirements failed on first attempt on Raspi 3B version, strangely 2nd attempt to install from requirements.txt worked.

Regardless, following error was noted 

```
`Exception:
Traceback (most recent call last):
  File "/home/pi/github/miu/scurid/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/pi/github/miu/scurid/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/github/miu/scurid/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:`
```

**Comment by bootstrapsp** [comment]
While miu itself runs, running into issue with the libindy.so error 

```
ERROR:indy.libindy:_load_cdll: Can't load libindy: libindy.so: cannot open shared object file: No such file or directory
ERROR:wallet_service:Exception Occurred @ GenerateWalletKey------
ERROR:wallet_service:libindy.so: cannot open shared object file: No such file or directory
```

**Comment by bootstrapsp** [comment]
building the libindy from source from the [doc](https://github.com/hyperledger/indy-sdk/blob/master/docs/build-guides/ubuntu-build.md )

failing to compile due to memory exhaustion

```
 = note: /usr/lib/arm-linux-gnueabihf/libutil.so: error adding symbols: Memory exhausted
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `libindy`.
```
